-- Drop Statements

-- Triggers & Stored Procedures

-- Insert Statements
INSERT INTO SurfaceRoadNumbers (street_number) VALUES
                               (1421),
                               (1500),
                               (1621),
                               (2413),
                               (2900),
                               (2850),
                               (3030),
                               (3333),
                               (3361),
                               (3601),
                               (3705),
                               (3811),
                               (3814),
                               (3930),
                               (3941),
                               (3960),
                               (6561),
                               (7979),
                               (12775),
                               (14532),
                               (15062),
                               (15122),
                               (16122),
                               (16428),
                               (16811),
                               (16866),
                               (18575),
                               (18645),
                               (19692),
                               (23641),
                               (17931);

INSERT INTO SurfaceRoadDirections (abbreviation, street_heading) VALUES
                                  ('S', 'South'),
                                  ('SW', 'South-West'),
                                  ('W', 'West'),
                                  ('NW', 'North-West'),
                                  ('N', 'North'),
                                  ('NE', 'North-East'),
                                  ('E', 'East'),
                                  ('SE', 'South-East');

INSERT INTO SurfaceRoadNames (street_name) VALUES
                             ('1st'),
                             ('17th'),
                             ('Adams'),
                             ('Beach'),
                             ('Bolsa'),
                             ('Bristol'),
                             ('Chapman'),
                             ('Center'),
                             ('Dyer'),
                             ('Edinger'),
                             ('Fairview'),
                             ('Goldenwest'),
                             ('Harbor'),
                             ('Jamboree'),
                             ('MacArthur'),
                             ('Main'),
                             ('McFadden'),
                             ('Newhope'),
                             ('Pacific Coast Highway'),
                             ('Rockfield'),
                             ('Segerstrom'),
                             ('Slater'),
                             ('Sunflower'),
                             ('Talbert'),
                             ('Warner'),
                             ('Westminster');

INSERT INTO SurfaceRoadSuffixes (street_suffix, street_suffix_long) VALUES
                                ('ave', 'Avenue'),
                                ('blvd', 'Boulevard'),
                                ('ct', 'Court'),
                                ('dr', 'Drive'),
                                ('pkwy', 'Parkway'),
                                ('rd', 'Road'),
                                ('st', 'Street');


INSERT INTO Cities (city_name) VALUES
                   ('Anaheim'),
                   ('Costa Mesa'),
                   ('Columbus'),
                   ('Huntington Beach'),
                   ('Irvine'),
                   ('Lake Forest'),
                   ('Newport Beach'),
                   ('San Francisco'),
                   ('Santa Ana'),
                   ('Tacoma'),
                   ('Tustin'),
                   ('Westminster');

INSERT INTO States (state_code, state_name) VALUES
                   ('AZ', 'Arizona'),
                   ('CA', 'California'),
                   ('DE', 'Delaware'),
                   ('FL', 'Florida'),
                   ('GA', 'Georgia'),
                   ('IL', 'Illinois'),
                   ('IN', 'Indiana'),
                   ('NV', 'Nevada'),
                   ('OR', 'Oregon'),
                   ('WA', 'Washington');

INSERT INTO countries (country_code, country_name) VALUES
                      ('US', 'United States of America'),
                      ('UK', 'United Kingdom'),
                      ('MX', 'Mexico'),
                      ('DE', 'Germany'),
                      ('PT', 'Portugal'),
                      ('CW', 'Curaçao'),
                      ('ID', 'Indonesia'),
                      ('NG', 'Nigeria'),
                      ('RW', 'Rwanda'),
                      ('SK', 'Slovakia');

INSERT INTO LocationTypes (type, type_long) VALUES
                          ('Unit', 'Unit'),
                          ('Ste', 'Suite'),
                          ('Spc', 'Space');

INSERT INTO LocationSeparators (separator) VALUES
                               ('A'),
                               ('B'),
                               ('C'),
                               ('D'),
                               ('G'),
                               ('H'),
                               ('106'),
                               ('100A'),
                               ('G3'),
                               ('102');

INSERT INTO chainrestaurants (chain_website, chain_name) VALUES
                             ('http://aloha-hawaiianbbq.com/menu.html', 'Aloha Hawaiian BBQ'),
                             ('https://www.buffalowildwings.com/en/', 'Buffalo Wild Wings'),
                             ('https://www.bk.com/', 'Burger King'),
                             ('https://www.chick-fil-a.com/', 'Chick-fil-A'),
                             ('https://www.chipotle.com/', 'Chipotle'),
                             ('https://www.cornerbakerycafe.com/', 'Corner Bakery'),
                             ('http://www.fiveguys.com/', 'Five Guys'),
                             ('https://www.in-n-out.com/', 'In-N-Out Burger'),
                             ('https://www.jerseymikes.com/', 'Jersey Mike''s'),
                             ('https://www.jimmyjohns.com/', 'Jimmy John''s'),
                             ('https://www.kfc.com/', 'KFC'),
                             ('https://www.hawaiianbarbecue.com/', 'L&L Hawaiian BBQ'),
                             ('https://www.mcdonalds.com/us/en-us.html', 'McDonald''s'),
                             ('https://www.olivegarden.com/home', 'Olive Garden'),
                             ('https://www.pandaexpress.com/', 'Panda Express'),
                             ('https://www.panerabread.com/en-us/home.html', 'Panera Bread'),
                             ('https://www.popeyes.com/', 'Popeye''s'),
                             ('https://www.raisingcanes.com/', 'Raising Cane''s Chicken Fingers'),
                             ('https://www.rittersskc.com/', 'Ritter''s Steam Kettle Cooking'),
                             ('https://www.roundtablepizza.com/', 'Round Table Pizza'),
                             ('https://order.subway.com/en-us/', 'Subway'),
                             ('https://www.tacobell.com/', 'Taco Bell'),
                             ('https://www.habitburger.com/', 'The Habit Hamburger Grill'),
                             ('https://thehat.com/', 'The Hat'),
                             ('https://www.togos.com/', 'Togo''s Sandwiches');

INSERT INTO ZipLocations (zip_code, city_name, state_code, country_code) VALUES
                         ('31905', 'Columbus', 'GA', 'US'),
                         ('90680', 'Westminster', 'CA', 'US'),
                         ('92626', 'Costa Mesa', 'CA', 'US'),
                         ('92630', 'Lake Forest', 'CA', 'US'),
                         ('92647', 'Huntington Beach', 'CA', 'US'),
                         ('92648', 'Huntington Beach', 'CA', 'US'),
                         ('92683', 'Westminster', 'CA', 'US'),
                         ('92704', 'Santa Ana', 'CA', 'US'),
                         ('92707', 'Santa Ana', 'CA', 'US'),
                         ('92703', 'Santa Ana', 'CA', 'US'),
                         ('98433', 'Tacoma', 'WA', 'US');

INSERT INTO Addresses (street_number, street_name, zip_code) VALUES
                      (3814, 'Bristol', '92704'),
                      (7979, 'Center', '92647'),
                      (3811, 'Bristol', '92704'),
                      (2850, 'Bristol', '92704'),
                      (3601, 'Bristol', '92704'),
                      (3705, 'Bristol', '92704'),
                      (1621, 'Sunflower', '92704'),
                      (2413, 'Fairview', '92704'),
                      (2900, 'Warner', '92704'),
                      (3030, 'Harbor', '92626'),
                      (3361, 'Bristol', '92704'),
                      (3941, 'Bristol', '92704'),
                      (3930, 'Bristol', '92704'),
                      (19692, 'Beach', '92648'),
                      (3333, 'Bristol', '92626'),
                      (16428, 'Beach', '92683'),
                      (6561, 'Edinger', '92647'),
                      (16866, 'Beach', '92647'),
                      (3960, 'Main', '92707'),
                      (16811, 'Beach', '92647'),
                      (18575, 'Beach', '92648'),
                      (16428, 'Beach', '92683'),
                      (14532, 'Beach', '92683'),
                      (12775, 'Beach', '90680'),
                      (1421, 'MacArthur', '92704'),
                      (16122, 'Goldenwest', '92647'),
                      (1500, 'Adams', '92626'),
                      (15122, 'Goldenwest', '92683'),
                      (18645, 'Beach', '92648'),
                      (23641, 'Rockfield', '92630'),
                      (17931, 'Beach', '92647');

INSERT INTO AddressDirections (address_id, street_direction) VALUES
                              (1, 'S'),
                              (2, 'W'),
                              (3, 'N'),
                              (4, 'S'),
                              (5, 'N'),
                              (6, 'N'),
                              (7, 'W'),
                              (8, 'N'),
                              (9, 'E'),
                              (10, 'N'),
                              (11, 'N'),
                              (12, 'N'),
                              (13, 'S'),
                              (14, 'N'),
                              (15, 'S'),
                              (16, 'N'),
                              (17, 'W'),
                              (18, 'N'),
                              (19, 'S'),
                              (20, 'S'),
                              (21, 'S'),
                              (22, 'N'),
                              (23, 'N'),
                              (24, 'S'),
                              (25, 'W'),
                              (26, 'N'),
                              (27, 'W'),
                              (28, 'N'),
                              (29, 'S'),
                              (30, 'NW'),
                              (31, 'S');

INSERT INTO AddressSuffixes (address_id, street_suffix) VALUES
                            (1, 'st'),
                            (2, 'ave'),
                            (3, 'st'),
                            (4, 'st'),
                            (5, 'st'),
                            (6, 'st'),
                            (7, 'ave'),
                            (8, 'st'),
                            (9, 'ave'),
                            (10, 'blvd'),
                            (11, 'st'),
                            (12, 'st'),
                            (13, 'st'),
                            (14, 'blvd'),
                            (15, 'st'),
                            (16, 'blvd'),
                            (17, 'blvd'),
                            (18, 'blvd'),
                            (19, 'st'),
                            (20, 'blvd'),
                            (21, 'blvd'),
                            (22, 'blvd'),
                            (23, 'blvd'),
                            (24, 'blvd'),
                            (25, 'blvd'),
                            (26, 'st'),
                            (27, 'ave'),
                            (28, 'st'),
                            (29, 'blvd'),
                            (30, 'blvd'),
                            (31, 'blvd');

INSERT INTO Locations (location_type, location_space) VALUES
                      ('Unit', 'B'),
                      ('Unit', 'D'),
                      ('Unit', 'G'),
                      ('Unit', 'H'),
                      ('Unit', '106'),
                      ('Unit', '100A'),
                      ('Unit', 'A'),
                      ('Ste', 'A'),
                      ('Ste', 'B'),
                      ('Ste', 'D'),
                      ('Spc', 'G3'),
                      ('Ste', '102');

INSERT INTO ChainRestaurantLocations (chain_name, restaurant_phone, address_id) VALUES
                                     ('Aloha Hawaiian BBQ', '7149571134', 1),
                                     ('Buffalo Wild Wings', '7145401737', 3),
                                     ('Burger King', '7149756126', 4),
                                     ('Chick-fil-A', '7145400020', 5),
                                     ('Chipotle', '7147547380', 6),
                                     ('Corner Bakery', '7145461555', 7),
                                     ('Five Guys', '7148614448', 29),
                                     ('In-N-Out Burger', '8007861000', 11),
                                     ('Jersey Mike''s', '7144381300', 12),
                                     ('Jimmy John''s', '7145404040', 31),
                                     ('L&L Hawaiian BBQ', '7149681898', 14),
                                     ('McDonald''s', '7148951476', 17),
                                     ('McDonald''s', '7148481361', 18),
                                     ('Olive Garden', '7148478874', 20),
                                     ('Panda Express', '7143759338', 21),
                                     ('Panera Bread', '7148435600', 10),
                                     ('Popeye''s', '7148988151', 23),
                                     ('Raising Cane''s Chicken Fingers', '7143730188', 24),
                                     ('Round Table Pizza', '7148475517', 26),
                                     ('The Habit Hamburger Grill', '6577770877', 28),
                                     ('The Hat', '9495869200', 30);

INSERT INTO locationunits (location_type, location_space, restaurant_id) VALUES
                          ('Unit', 'B', 1),
                          (8, 'Unit', 'H'),
                          ('Unit', 'G', 9),
                          ('Unit', '106', 10),
                          (19, 'Unit', 'D'),
                          (25, 'Unit', 'G'),
                          (27, 'Unit', '100A'),
                          (28, 'Ste', 'A'),
                          (10, 'Spc', 'G3'),
                          (31, 'Ste', '102');

INSERT INTO SoloRestaurants (restaurant_name, restaurant_phone, restaurant_website, address_id) VALUES
                            ('Buca di Beppo', '7148914666', 'https://www.bucadibeppo.com/', 2),
                            ('Don Jacinto''s Pollo Grill', '7144340821', 'http://orderdonjacintopollogrill.com/', 8),
                            ('Duke''s', '7145575480', 'no website', 9),
                            ('Maggiano''s Little Italy', '7145469550', 'https://www.maggianos.com/', 15),
                            ('Maui Hawaiian BBQ', '7145967299', 'https://www.mauihawaiianbbqca.com/', 16),
                            ('Nate''s Korner', '7145455772', 'http://www.nateskorner.com/', 19),
                            ('Ritter''s Steam Kettle Cooking', '7148501380', 'https://www.rittersskc.com/', 25),
                            ('Tandoori Fresh', '7144444407', 'unsafe', 27);

INSERT INTO Meals (meal_name) VALUES
                  ('breakfast'),
                  ('lunch'),
                  ('dinner'),
                  ('all'),
                  ('lunch-dinner');

INSERT INTO ChainRestaurantMeals ( meal_name, restaurant_id) VALUES
                                 ('lunch-dinner', 1),
                                ('lunch-dinner', 2),
                                ('all', 3),
                                ('all', 4),
                                ('lunch-dinner', 5),
                                ('all', 6),
                                ('lunch-dinner', 7),
                                ('lunch-dinner', 8),
                                ('lunch-dinner', 9),
                                ('lunch-dinner', 10),
                                ('lunch-dinner', 11),
                                ('all', 12),
                                ('all', 13),
                                ('lunch-dinner', 14),
                                ('lunch-dinner', 15),
                                ('all', 16),
                                ('lunch-dinner', 17),
                                ('lunch-dinner', 18),
                                ('lunch-dinner', 19),
                                ('lunch-dinner', 20),
                                ('lunch-dinner', 21);

INSERT INTO SoloRestaurantMeals (meal_name, restaurant_phone) VALUES
                                ('lunch', '7148914666'),
                                ('dinner', '7148914666'),
                                ('lunch', '7144340821'),
                                ('dinner', '7144340821'),
                                ('breakfast', '7145575480'),
                                ('lunch', '7145575480'),
                                ('dinner', '7145575480'),
                                ('lunch', '7145469550'),
                                ('dinner', '7145469550'),
                                ('lunch', '7145967299'),
                                ('dinner', '7145967299'),
                                ('breakfast', '7145455772'),
                                ('lunch', '7145455772'),
                                ('dinner', '7145455772'),
                                ('lunch', '7148501380'),
                                ('dinner', '7148501380'),
                                ('lunch', '7144444407'),
                                ('dinner', '7144444407');

INSERT INTO Days (day_abbreviation, day_name) VALUES
                 ('Su', 'Sunday'),
                 ('Mo', 'Monday'),
                 ('Tu', 'Tuesday'),
                 ('We', 'Wednesday'),
                 ('Tr', 'Thursday'),
                 ('Fr', 'Friday'),
                 ('Sa', 'Saturday');

INSERT INTO Hours (time) VALUES
                  ('01:00'),
                  ('01:30'),
                  ('02:00'),
                  ('02:30'),
                  ('03:00'),
                  ('03:30'),
                  ('04:00'),
                  ('04:30'),
                  ('05:00'),
                  ('05:30'),
                  ('06:00'),
                  ('06:30'),
                  ('07:00'),
                  ('07:30'),
                  ('08:00'),
                  ('08:30'),
                  ('09:00'),
                  ('09:30'),
                  ('10:00'),
                  ('10:30'),
                  ('11:00'),
                  ('11:30'),
                  ('12:00'),
                  ('12:30'),
                  ('13:00'),
                  ('13:30'),
                  ('14:00'),
                  ('14:30'),
                  ('15:00'),
                  ('15:30'),
                  ('16:00'),
                  ('16:30'),
                  ('17:00'),
                  ('17:30'),
                  ('18:00'),
                  ('18:30'),
                  ('19:00'),
                  ('19:30'),
                  ('20:00'),
                  ('20:30'),
                  ('21:00'),
                  ('21:30'),
                  ('22:00'),
                  ('22:30'),
                  ('23:00'),
                  ('23:30'),
                  ('24:00');

INSERT INTO ChainRestaurantOperations (restaurant_id, day_abbreviation, meal_name, opening_time, closing_time) VALUES
                                      (1, 'Su', 'lunch-dinner', '10:30', '20:00'),
                                      (1, 'Mo', 'lunch-dinner', '10:30', '20:00'),
                                      (1, 'Tu', 'lunch-dinner', '10:30', '20:00'),
                                      (1, 'We', 'lunch-dinner', '10:30', '20:00'),
                                      (1, 'Tr', 'lunch-dinner', '10:30', '20:00'),
                                      (1, 'Fr', 'lunch-dinner', '10:30', '20:30'),
                                      (1, 'Sa', 'lunch-dinner', '10:30', '20:30'),
                                      (2, 'Su', 'lunch-dinner', '11:00', '24:00'),
                                      (2, 'Mo', 'lunch-dinner', '11:00', '24:00'),
                                      (2, 'Tu', 'lunch-dinner', '11:00', '24:00'),
                                      (2, 'We', 'lunch-dinner', '11:00', '24:00'),
                                      (2, 'Tr', 'lunch-dinner', '11:00', '02:00'),
                                      (2, 'Fr', 'lunch-dinner', '11:00', '02:00'),
                                      (2, 'Sa', 'lunch-dinner', '11:00', '02:00'),
                                      (3, 'Su', 'all', '07:00', '23:30'),
                                      (3, 'Mo', 'all', '06:00', '23:30'),
                                      (3, 'Tu', 'all', '06:00', '23:30'),
                                      (3, 'We', 'all', '06:00', '23:30'),
                                      (3, 'Tr', 'all', '06:00', '23:30'),
                                      (3, 'Fr', 'all', '06:00', '23:30'),
                                      (3, 'Sa', 'all', '06:00', '23:30'),
                                      (4, 'Mo', 'all', '06:30', '23:00'),
                                      (4, 'Tu', 'all', '06:30', '23:00'),
                                      (4, 'We', 'all', '06:30', '22:30'),
                                      (4, 'Tr', 'all', '06:30', '23:00'),
                                      (4, 'Fr', 'all', '06:30', '23:00'),
                                      (4, 'Sa', 'all', '06:30', '23:00'),
                                      (5, 'Su', 'lunch-dinner', '10:30', '22:00'),
                                      (5, 'Mo', 'lunch-dinner', '10:30', '22:00'),
                                      (5, 'Tu', 'lunch-dinner', '10:30', '22:00'),
                                      (5, 'We', 'lunch-dinner', '10:30', '22:00'),
                                      (5, 'Tr', 'lunch-dinner', '10:30', '22:00'),
                                      (5, 'Fr', 'lunch-dinner', '10:30', '22:00'),
                                      (5, 'Sa', 'lunch-dinner', '10:30', '22:00'),
                                      (6, 'Su', 'all', '07:30', '19:30'),
                                      (6, 'Mo', 'all', '07:30', '19:30'),
                                      (6, 'Tu', 'all', '07:30', '19:30'),
                                      (6, 'We', 'all', '07:30', '19:30'),
                                      (6, 'Tr', 'all', '07:30', '19:30'),
                                      (6, 'Fr', 'all', '07:30', '19:30'),
                                      (6, 'Sa', 'all', '07:30', '19:30'),
                                      (7, 'Su', 'lunch-dinner', '11:00', '22:00'),
                                      (7, 'Mo', 'lunch-dinner', '11:00', '22:00'),
                                      (7, 'Tu', 'lunch-dinner', '11:00', '22:00'),
                                      (7, 'We', 'lunch-dinner', '11:00', '22:00'),
                                      (7, 'Tr', 'lunch-dinner', '11:00', '22:00'),
                                      (7, 'Fr', 'lunch-dinner', '11:00', '22:00'),
                                      (7, 'Sa', 'lunch-dinner', '11:00', '22:00'),
                                      (8, 'Su', 'lunch-dinner', '10:30', '01:00'),
                                      (8, 'Mo', 'lunch-dinner', '10:30', '01:00'),
                                      (8, 'Tu', 'lunch-dinner', '10:30', '01:00'),
                                      (8, 'We', 'lunch-dinner', '10:30', '01:00'),
                                      (8, 'Tr', 'lunch-dinner', '10:30', '01:00'),
                                      (8, 'Fr', 'lunch-dinner', '10:30', '01:30'),
                                      (8, 'Sa', 'lunch-dinner', '10:30', '01:30'),
                                      (9, 'Su', 'lunch-dinner', '10:00', '21:00'),
                                      (9, 'Mo', 'lunch-dinner', '10:00', '21:00'),
                                      (9, 'Tu', 'lunch-dinner', '10:00', '21:00'),
                                      (9, 'We', 'lunch-dinner', '10:00', '21:00'),
                                      (9, 'Tr', 'lunch-dinner', '10:00', '21:00'),
                                      (9, 'Fr', 'lunch-dinner', '10:00', '21:00'),
                                      (9, 'Sa', 'lunch-dinner', '10:00', '21:00'),
                                      (10, 'Su', 'lunch-dinner', '11:00', '22:00'), -- Repleace
                                      (10, 'Mo', 'lunch-dinner', '11:00', '22:00'), -- Repleace
                                      (10, 'Tu', 'lunch-dinner', '11:00', '22:00'), -- Repleace
                                      (10, 'We', 'lunch-dinner', '11:00', '22:00'), -- Repleace
                                      (10, 'Tr', 'lunch-dinner', '11:00', '22:00'), -- Repleace
                                      (10, 'Fr', 'lunch-dinner', '11:00', '22:00'), -- Repleace
                                      (10, 'Sa', 'lunch-dinner', '11:00', '22:00'), -- Repleace
                                      (11, 'Su', 'lunch-dinner', '11:00', '20:30'),
                                      (11, 'Mo', 'lunch-dinner', '11:00', '20:30'),
                                      (11, 'Tu', 'lunch-dinner', '11:00', '20:30'),
                                      (11, 'We', 'lunch-dinner', '11:00', '20:30'),
                                      (11, 'Tr', 'lunch-dinner', '11:00', '20:30'),
                                      (11, 'Fr', 'lunch-dinner', '11:00', '20:30'),
                                      (11, 'Sa', 'lunch-dinner', '11:00', '20:30'),
                                      (12, 'Su', 'all', '06:00', '23:00'),
                                      (12, 'Mo', 'all', '06:00', '23:00'),
                                      (12, 'Tu', 'all', '06:00', '23:00'),
                                      (12, 'We', 'all', '06:00', '23:00'),
                                      (12, 'Tr', 'all', '06:00', '23:00'),
                                      (12, 'Fr', 'all', '06:00', '23:00'),
                                      (12, 'Sa', 'all', '06:00', '23:00'),
                                      (13, 'Su', 'all', '05:30', '02:00'),
                                      (13, 'Mo', 'all', '05:30', '01:00'),
                                      (13, 'Tu', 'all', '05:30', '01:00'),
                                      (13, 'We', 'all', '05:30', '01:00'),
                                      (13, 'Tr', 'all', '05:30', '01:00'),
                                      (13, 'Fr', 'all', '05:30', '01:00'),
                                      (13, 'Sa', 'all', '05:30', '02:00'),
                                      (14, 'Su', 'lunch-dinner', '11:00', '20:00'),
                                      (14, 'Mo', 'lunch-dinner', '11:00', '20:00'),
                                      (14, 'Tu', 'lunch-dinner', '11:00', '20:00'),
                                      (14, 'We', 'lunch-dinner', '11:00', '20:00'),
                                      (14, 'Tr', 'lunch-dinner', '11:00', '20:00'),
                                      (14, 'Fr', 'lunch-dinner', '11:00', '23:00'),
                                      (14, 'Sa', 'lunch-dinner', '11:00', '23:00'),
                                      (15, 'Su', 'lunch-dinner', '10:00', '22:00'),
                                      (15, 'Mo', 'lunch-dinner', '10:00', '22:00'),
                                      (15, 'Tu', 'lunch-dinner', '10:00', '22:00'),
                                      (15, 'We', 'lunch-dinner', '10:00', '22:00'),
                                      (15, 'Tr', 'lunch-dinner', '10:00', '22:00'),
                                      (15, 'Fr', 'lunch-dinner', '10:00', '22:00'),
                                      (15, 'Sa', 'lunch-dinner', '10:00', '22:00'),
                                      (16, 'Su', 'all', '07:00', '20:30'),
                                      (16, 'Mo', 'all', '07:00', '20:30'),
                                      (16, 'Tu', 'all', '07:00', '20:30'),
                                      (16, 'We', 'all', '07:00', '20:30'),
                                      (16, 'Tr', 'all', '07:00', '20:30'),
                                      (16, 'Fr', 'all', '07:00', '21:00'),
                                      (16, 'Sa', 'all', '07:00', '21:00'),
                                      (17, 'Su', 'lunch-dinner', '10:00', '02:00'),
                                      (17, 'Mo', 'lunch-dinner', '10:00', '22:00'),
                                      (17, 'Tu', 'lunch-dinner', '10:00', '22:00'),
                                      (17, 'We', 'lunch-dinner', '10:00', '22:00'),
                                      (17, 'Tr', 'lunch-dinner', '10:00', '22:00'),
                                      (17, 'Fr', 'lunch-dinner', '10:00', '22:00'),
                                      (17, 'Sa', 'lunch-dinner', '10:00', '22:00'),
                                      (18, 'Su', 'lunch-dinner', '09:00', '02:00'),
                                      (18, 'Mo', 'lunch-dinner', '09:00', '02:00'),
                                      (18, 'Tu', 'lunch-dinner', '09:00', '02:00'),
                                      (18, 'We', 'lunch-dinner', '09:00', '02:00'),
                                      (18, 'Tr', 'lunch-dinner', '09:00', '03:30'),
                                      (18, 'Fr', 'lunch-dinner', '09:00', '03:30'),
                                      (18, 'Sa', 'lunch-dinner', '09:00', '03:30'),
                                      (19, 'Su', 'lunch-dinner', '10:30', '21:00'),
                                      (19, 'Mo', 'lunch-dinner', '10:30', '21:00'),
                                      (19, 'Tu', 'lunch-dinner', '10:30', '21:00'),
                                      (19, 'We', 'lunch-dinner', '10:30', '21:00'),
                                      (19, 'Tr', 'lunch-dinner', '10:30', '21:00'),
                                      (19, 'Fr', 'lunch-dinner', '10:30', '22:00'),
                                      (19, 'Sa', 'lunch-dinner', '10:30', '22:00'),
                                      (20, 'Su', 'lunch-dinner', '10:30', '21:00'),
                                      (20, 'Mo', 'lunch-dinner', '10:30', '22:00'),
                                      (20, 'Tu', 'lunch-dinner', '10:30', '22:00'),
                                      (20, 'We', 'lunch-dinner', '10:30', '22:00'),
                                      (20, 'Tr', 'lunch-dinner', '10:30', '22:00'),
                                      (20, 'Fr', 'lunch-dinner', '10:30', '22:00'),
                                      (20, 'Sa', 'lunch-dinner', '10:30', '22:00'),
                                      (21, 'Su', 'lunch-dinner', '10:00', '23:00'),
                                      (21, 'Mo', 'lunch-dinner', '10:00', '23:00'),
                                      (21, 'Tu', 'lunch-dinner', '10:00', '23:00'),
                                      (21, 'We', 'lunch-dinner', '10:00', '23:00'),
                                      (21, 'Tr', 'lunch-dinner', '10:00', '23:00'),
                                      (21, 'Fr', 'lunch-dinner', '10:00', '23:00'),
                                      (21, 'Sa', 'lunch-dinner', '10:00', '23:00');